# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20161128_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserStats',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('nbFavoris', models.IntegerField()),
                ('nbPhotos', models.IntegerField()),
            ],
            options={
                'db_table': 'backoffice_userstatistiques',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='favoris',
            field=models.ManyToManyField(through='backoffice.Favori', to='backoffice.Lieu'),
        ),
    ]
